import type { Data, ProductFood } from './types'

export const products: ProductFood[] = [
  {
    __typename: 'ProductFood',
    pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
    sizeId: null,
    colorId: null,
    cId: null,
    dId: null,
    ctId: null,
    fId: null,
    pName: 'Test con muchos sub items',
    getOneTags: null,
    ProPrice: 5000,
    ProDescuento: '3',
    free: 0,
    ProUniDisponibles: null,
    ProDescription:
      'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    ProProtegido: null,
    ProAssurance: null,
    ValueDelivery: null,
    ProStar: 0,
    sTateLogistic: 1,
    ProImage:
      'https:https://front-back-server.onrender.comstatic/platos/undefined',
    ProWidth: null,
    ProHeight: null,
    ProLength: '1',
    ProWeight: '1',
    ProQuantity: null,
    ProOutstanding: 0,
    pDatCre: '2024-02-13T10:22:37.930Z',
    pDatMod: '2024-02-13T10:22:37.930Z',
    ProDelivery: 0,
    ProVoltaje: null,
    pState: 1,
    feat: null,
    area: null,
    comment: false,
    edit: false,
    onClick: () => {

    },
    render: '<IconSales />',
    tag: null
  },
  {
    __typename: 'ProductFood',
    pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
    sizeId: null,
    colorId: null,
    cId: null,
    dId: null,
    ctId: null,
    fId: null,
    pName: 'Test con muchos sub items',
    getOneTags: null,
    ProPrice: 5000,
    ProDescuento: '3',
    free: 0,
    ProUniDisponibles: null,
    ProDescription:
      'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    ProProtegido: null,
    ProAssurance: null,
    ValueDelivery: null,
    ProStar: 0,
    sTateLogistic: 1,
    ProImage:
      'https:https://front-back-server.onrender.comstatic/platos/undefined',
    ProWidth: null,
    ProHeight: null,
    ProLength: '1',
    ProWeight: '1',
    ProQuantity: null,
    ProOutstanding: 0,
    pDatCre: '2024-02-13T10:22:37.930Z',
    pDatMod: '2024-02-13T10:22:37.930Z',
    ProDelivery: 0,
    ProVoltaje: null,
    pState: 1,
    feat: null,
    area: null,
    comment: false,
    edit: false,
    onClick: () => {

    },
    render: '<IconSales />',
    tag: null
  },
  {
    __typename: 'ProductFood',
    pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
    sizeId: null,
    colorId: null,
    cId: null,
    dId: null,
    ctId: null,
    fId: null,
    pName: 'Test con muchos sub items',
    getOneTags: null,
    ProPrice: 5000,
    ProDescuento: '3',
    free: 0,
    ProUniDisponibles: null,
    ProDescription:
      'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    ProProtegido: null,
    ProAssurance: null,
    ValueDelivery: null,
    ProStar: 0,
    sTateLogistic: 1,
    ProImage:
      'https:https://front-back-server.onrender.comstatic/platos/undefined',
    ProWidth: null,
    ProHeight: null,
    ProLength: '1',
    ProWeight: '1',
    ProQuantity: null,
    ProOutstanding: 0,
    pDatCre: '2024-02-13T10:22:37.930Z',
    pDatMod: '2024-02-13T10:22:37.930Z',
    ProDelivery: 0,
    ProVoltaje: null,
    pState: 1,
    feat: null,
    area: null,
    comment: false,
    edit: false,
    onClick: () => {

    },
    render: '<IconSales />',
    tag: null
  },
  {
    __typename: 'ProductFood',
    pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
    sizeId: null,
    colorId: null,
    cId: null,
    dId: null,
    ctId: null,
    fId: null,
    pName: 'Test con muchos sub items',
    getOneTags: null,
    ProPrice: 5000,
    ProDescuento: '3',
    free: 0,
    ProUniDisponibles: null,
    ProDescription:
      'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    ProProtegido: null,
    ProAssurance: null,
    ValueDelivery: null,
    ProStar: 0,
    sTateLogistic: 1,
    ProImage:
      'https:https://front-back-server.onrender.comstatic/platos/undefined',
    ProWidth: null,
    ProHeight: null,
    ProLength: '1',
    ProWeight: '1',
    ProQuantity: null,
    ProOutstanding: 0,
    pDatCre: '2024-02-13T10:22:37.930Z',
    pDatMod: '2024-02-13T10:22:37.930Z',
    ProDelivery: 0,
    ProVoltaje: null,
    pState: 1,
    feat: null,
    area: null,
    comment: false,
    edit: false,
    onClick: () => {

    },
    render: '<IconSales />',
    tag: null
  },
  {
    __typename: 'ProductFood',
    pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
    sizeId: null,
    colorId: null,
    cId: null,
    dId: null,
    ctId: null,
    fId: null,
    pName: 'Test con muchos sub items',
    getOneTags: null,
    ProPrice: 5000,
    ProDescuento: '3',
    free: 0,
    ProUniDisponibles: null,
    ProDescription:
      'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    ProProtegido: null,
    ProAssurance: null,
    ValueDelivery: null,
    ProStar: 0,
    sTateLogistic: 1,
    ProImage:
      'https:https://front-back-server.onrender.comstatic/platos/undefined',
    ProWidth: null,
    ProHeight: null,
    ProLength: '1',
    ProWeight: '1',
    ProQuantity: null,
    ProOutstanding: 0,
    pDatCre: '2024-02-13T10:22:37.930Z',
    pDatMod: '2024-02-13T10:22:37.930Z',
    ProDelivery: 0,
    ProVoltaje: null,
    pState: 1,
    feat: null,
    area: null,
    comment: false,
    edit: false,
    onClick: () => {

    },
    render: '<IconSales />',
    tag: null
  }
]

export const data: Data = {
  PRODUCT: [
    {
      pId: '075c0df7-8ec2-2fdf-7db6-2b7b481c03bd',
      pName: 'Test con muchos sub items',
      unitPrice: 5000,
      ProDescription: 'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
      ProImage: 'https:https://front-back-server.onrender.comstatic/platos/undefined',
      ProPrice: 20000,
      ProQuantity: 4,
      free: false
    },
    {
      pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
      pName: 'Test con muchos sub items',
      unitPrice: 5000,
      ProDescription: '50000',
      ProImage: 'https:https://front-back-server.onrender.comstatic/platos/undefined',
      ProPrice: 20000,
      ProQuantity: 4,
      free: false,
      dataOptional: [
        {
          __typename: 'ExtProductFoodOptional',
          pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
          opExPid: 'f4029fb3-e329-96ce-31a1-f3005a23ea20',
          OptionalProName: 'CATEGORIA',
          state: 1,
          code: 'G0iKUbpk0',
          numbersOptionalOnly: 3,
          pDatCre: '2024-02-09T08:31:17.949Z',
          required: 0,
          pDatMod: '2024-02-09T08:31:17.949Z',
          ExtProductFoodsSubOptionalAll: [
            {
              __typename: 'ExtProductFoodSubOptional',
              pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
              opExPid: null,
              idStore: '013e5387-34a1-6a78-303d-5098f17bf640',
              opSubExPid: '44aa8ce5-e7be-bf62-cada-35b123343570',
              OptionalSubProName: 'SUB ITEM DE CATEGORIA 1',
              exCodeOptionExtra: 'G0iKUbpk0',
              exCode: 'fSfTj0uHe',
              state: 1,
              pDatCre: '2024-02-09T08:31:28.547Z',
              pDatMod: '2024-02-09T08:31:28.547Z',
              check: true
            },
            {
              __typename: 'ExtProductFoodSubOptional',
              pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
              opExPid: null,
              idStore: '013e5387-34a1-6a78-303d-5098f17bf640',
              opSubExPid: 'fca67b88-d2d0-e7b8-c93d-0d6625f12cf0',
              OptionalSubProName: 'SUB ITEM DE CATEGORIA 2',
              exCodeOptionExtra: 'G0iKUbpk0',
              exCode: 'ZuSm9PDN7',
              state: 1,
              pDatCre: '2024-02-09T08:31:30.460Z',
              pDatMod: '2024-02-09T08:31:30.460Z',
              check: true
            },
            {
              __typename: 'ExtProductFoodSubOptional',
              pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
              opExPid: null,
              idStore: '013e5387-34a1-6a78-303d-5098f17bf640',
              opSubExPid: '10cde7f6-e810-a82c-80e7-94daf39e4415',
              OptionalSubProName: 'SUB ITEM DE CATEGORIA 3',
              exCodeOptionExtra: 'G0iKUbpk0',
              exCode: 'o5d5HsGKx',
              state: 1,
              pDatCre: '2024-02-09T08:31:35.109Z',
              pDatMod: '2024-02-09T08:31:35.109Z',
              check: true
            }
          ]
        }
      ],
      dataExtra: [
        {
          __typename: 'ExtProductFood',
          pId: '486c7a48-1511-bc69-3ebf-13e8c04d2125',
          exPid: 'd677aae4-9d42-3274-a404-b9e3b47be8f2',
          exState: 0,
          extraName: 'PERO QUE PRECIO 1',
          extraPrice: 5000,
          state: 1,
          pDatCre: '2024-02-09T08:31:57.772Z',
          pDatMod: '2024-02-09T08:31:57.772Z',
          quantity: 3,
          newExtraPrice: 15000
        }
      ]
    }
  ],
  totalPrice: 0,
  sortBy: null,
  itemsInCart: 0,
  animateType: '',
  startAnimateUp: 'start-animate-up',
  priceRange: 0,
  counter: 8,
  totalAmount: 35000,
  payMethodPState: 0
}
